### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dojo90** [dojo90/NLogViewer#48]
- [ ] Implement `NLogViewer.Server`
- [ ] Implement `NLogViewer.Webinterface`
- [ ] Implement `NLogViewer.ClientApplication`

## NLogViewer.Server

.NET server application which can handle the `NLogViewerTarget` (https://github.com/NLog/NLog/wiki/NLogViewer-target) and provides the `NLogViewer.Webinterface`

## NLogViewer.Webinterface

Provides an extension method to add an webinterface to your .NET Server application.

Example call in your `Startup.cs`
```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
	app.UseNlogViewerWebinterface(new NLogViewerWebinterfaceOptions()
	{
		Path = "/nlogviewer"
	});
}
```

## NLogViewer.ClientApplication

Standalone application which can handle the `NLogViewerTarget`.

---

Please feel free to contribute

**Comment by danielmeza** [comment]
The web interface should be like the swagger ui? enbebend into the the assembly and independent from the host web site?

**Comment by dojo90** [comment]
Hi Daniel,
Thank you for your feedback signal.
I think the look of the UI would be secondary in my opinion. I regularly run a .net server application and also a client application. In order to evaluate the logs on the server, I have to access the server remotely and read the logs there using Sentinel.

It would be easier and more comfortable to start Firefox/Chrome and use https://serverIP/nlogviewer to look at the logs. 
*The communication between server and client is already web-based.*
